# Generated by Django 4.1.6 on 2023-02-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='phonebook.persone')),
            ],
        ),
    ]
