# Generated by Django 4.1.6 on 2023-02-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_persone_name_alter_phone_phone_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='phone',
            new_name='email',
        ),
    ]
